[package]
name = "zipkin-core"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
error-chain = "0.10"
time = "0.1"
rand = "0.3"
xoroshiro128 = "0.2"

bytes = "0.4"
tokio-io = "0.1"
