[package]
name = "zipkin"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
error-chain = "0.10"
chrono = "0.3"
rand = "0.3"
xoroshiro128 = "0.2"
futures = "0.1"
futures-cpupool = "0.1"