sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=zipkin
install:
  - cargo install cargo-tree --force
script:
  - cargo test --all
  - cd zipkin && cargo run --example simple_proxy -- -h
after_failure:
  - cd zipkin && cargo tree
  - tree -h
cache:
  cargo: true
  directories:
    - $HOME/.cargo
