[package]
name = "zipkin-kafka"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
error-chain = "0.10"
kafka = { git = "https://github.com/flier/kafka-rust.git", branch = "openssl-0.9" }

zipkin-core = { path = "../zipkin-core" }