[package]
name = "zipkin-async"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
error-chain = "0.10"
futures = "0.1"
futures-cpupool = "0.1"
bytes = "0.4"
tokio-io = "0.1"

zipkin-core = { path = "../zipkin-core" }